[package]
name = "storage-service-types"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Common types offered by the Aptos storage service"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bcs = "0.1.3"
num-traits = { version = "0.2.15", default-features = false }
once_cell = "1.10.0"
serde = { version = "1.0.137", default-features = false }
snap = "1.0.5"
thiserror = "1.0.31"

aptos-config = { path = "../../../config" }
aptos-crypto = { path = "../../../crates/aptos-crypto" }
aptos-logger = { path = "../../../crates/aptos-logger" }
aptos-metrics-core = { path = "../../../crates/aptos-metrics-core" }
aptos-types = { path = "../../../types" }

[dev-dependencies]
claim = "0.5.0"
proptest = "1.0.0"
